--------------------------------------------------------
-- Archivo creado  - viernes-febrero-24-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HOTELUNO
--------------------------------------------------------

   CREATE SEQUENCE  "HOTELUNO"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTADO
--------------------------------------------------------

   CREATE SEQUENCE  "INCREMENTADO"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTADOIDCLIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "INCREMENTADOIDCLIENTE"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 34 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTADOIDHOTEL
--------------------------------------------------------

   CREATE SEQUENCE  "INCREMENTADOIDHOTEL"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTADOIDVUELO
--------------------------------------------------------

   CREATE SEQUENCE  "INCREMENTADOIDVUELO"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 35 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTANDOIDUSUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "INCREMENTANDOIDUSUARIO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence UNO
--------------------------------------------------------

   CREATE SEQUENCE  "UNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CLIENTE" 
   (	"ID" NUMBER(*,0), 
	"CEDULA" VARCHAR2(10 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(60 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "HOTEL" 
   (	"IDHOTEL" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"UBICACION" VARCHAR2(60 BYTE), 
	"TELEFONO" VARCHAR2(12 BYTE), 
	"DISPONIBILIDAD" VARCHAR2(2 BYTE), 
	"SERVICIOS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Table VUELO
--------------------------------------------------------

  CREATE TABLE "VUELO" 
   (	"IDVUELO" NUMBER(*,0), 
	"NOMBREAEROLINEA" VARCHAR2(40 BYTE), 
	"ORIGEN" VARCHAR2(40 BYTE), 
	"DESTINO" VARCHAR2(40 BYTE), 
	"ESCALA" VARCHAR2(40 BYTE), 
	"DISPONIBILIDAD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for View CONSUL_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "CONSUL_CLIENTES" ("ID", "CEDULA", "NOMBRES", "APELLIDOS", "TELEFONO", "DIRECCION", "EMAIL") AS 
  SELECT "ID","CEDULA","NOMBRES","APELLIDOS","TELEFONO","DIRECCION","EMAIL" FROM CLIENTE ORDER BY ID
;
--------------------------------------------------------
--  DDL for View EJEMPLO
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "EJEMPLO" ("ID", "CEDULA", "NOMBRES", "APELLIDOS", "TELEFONO", "DIRECCION", "EMAIL") AS 
  SELECT "ID","CEDULA","NOMBRES","APELLIDOS","TELEFONO","DIRECCION","EMAIL" FROM CLIENTE ORDER BY NOMBRES
;
REM INSERTING into CLIENTE
SET DEFINE OFF;
Insert into CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('56','0711654648','JHONNY ABELARDO','MARTINEZ CASTRO','0991916005','EL ORO-MACHALA','JAMARTINEZ99@GMAIL.COM');
Insert into CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('6','0955147871','ANGELA ','VERA SALAZAR','0915165156','GUAYAS-SAMBORONDON','ANGELA12@GMAIL.COM');
Insert into CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('33','0954310736','MAXIMILIANO STALIN','CABRERA','0962712966','SAMBORONDON','MAXIMILIANOCABRERA885@GMAIL.COM');
Insert into CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('24','0412121215','JORGE','LOOR ','0984542312','COLIMES','LOORJOR@GMAIL.COM');
Insert into CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('5','0954310785','LADY STEFANIA ','SEGURA GAMBOA','0915156165','SAMBORONDON','LADYSEGURA885@GMAIL.COM');
Insert into CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('55','1215451451','ISABEL','MONTOYA','0915313216','LOJA','ISABELITAMON@HOTMAIL.COM');
Insert into CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('54','0925454878','DERIAN AARON','RIVERA MURILLO','0951314515','DAULE','DERIANRIVERA16@GMAIL.COM');
REM INSERTING into HOTEL
SET DEFINE OFF;
Insert into HOTEL (IDHOTEL,NOMBRE,UBICACION,TELEFONO,DISPONIBILIDAD,SERVICIOS) values ('1','BOSTON HOTEL','PADRE VICENTE SOLANO VARGAS, GUAYAQUIL 090312','042308015','SI','WIFI, ESTACIONAMIENTO');
Insert into HOTEL (IDHOTEL,NOMBRE,UBICACION,TELEFONO,DISPONIBILIDAD,SERVICIOS) values ('6','NATIONAL HOTEL','1677 COLLINS AVE, MIAMI BEACH, FL , ESTADOS UNIDOS','13055322311','SI','WIFI, DESAYUNO, PISCINA, ESTACIONAMIENTO, AIRE ACONDICIONADO');
Insert into HOTEL (IDHOTEL,NOMBRE,UBICACION,TELEFONO,DISPONIBILIDAD,SERVICIOS) values ('2','HOTEL PALACE ','R448+WVP, CHILE, GUAYAQUIL 090313','042321080','SI','WIFI, DESAYUNO, ESTACIONAMIENTO');
Insert into HOTEL (IDHOTEL,NOMBRE,UBICACION,TELEFONO,DISPONIBILIDAD,SERVICIOS) values ('7','MIAMI GARDENS INN AND SUITES','16805 NW 12TH AVE, MIAMI, FL 33169, ESTADOS UNIDOS','17866617070','SI','WIFI, PISCINA, ESTACIONAMIENTO, AIRE ACONDICIONADO');
Insert into HOTEL (IDHOTEL,NOMBRE,UBICACION,TELEFONO,DISPONIBILIDAD,SERVICIOS) values ('8','FREEHAND MIAMI','2727 INDIAN CREEK DR, MIAMI BEACH, FL 33140, ESTADOS UNIDOS','13055312727','SI','WIFI, ESTACIONAMIENTO, ACCESO A LA PLAYA, PISCINA');
Insert into HOTEL (IDHOTEL,NOMBRE,UBICACION,TELEFONO,DISPONIBILIDAD,SERVICIOS) values ('3','HOTEL LILLAX','V36V+9J6, AV. FRANCISCO DE ORELLANA, GUAYAQUIL 090508','0939039894','SI','ESTACIONAMIENTO');
REM INSERTING into VUELO
SET DEFINE OFF;
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('15','AMERICAN AIRLINES ','GUAYAQUIL','SAN FRANCISCO','PANAMA','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('5','AEROMEXICO','GUAYAQUIL','CIUDAD DE MEXICO','QUITO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('10','AIR EUROPA','GUAYAQUIL','LONDRES','NEW YORK','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('20','AEROPUBLICA','QUITO','CIUDA DE MEXICO','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('22','AEROPUBLICA ','GUAYAQUIL','MIAMI','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('27','CONVIASA','GUAYAQUIL','MIAMI','CIUDAD DE MEXICO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('28','AMERICAN AIRLINES ','QUITO','NEW YORK','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('33','COPA','GUAYAQUIL','NEW YORK','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('1','TAME ','QUITO','MIAMI','PANAMA','NO');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('6','AEROMEXICO','QUITO','MONTERREY ','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('11','AIR EUROPA','QUITO','LONDRES','MIAMI','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('16','AEROMEXICO','GUAYAQUIL','BOGOTA','QUITO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('21','AEROPUBLICA','GUAYAQUIL','CIUDAD DE MEXICO','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('23','AEROPUBLICA','QUITO','MIAMI','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('29','AEROMEXICO','GUAYAQUIL','NEW YORK','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('34','COPA ','QUITO','NEW YORK','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('7','AMERICAN AIRLINES ','GUAYAQUIL','NEW YORK','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('12','AEROPUBLICA ','GUAYAQUIL','QUITO','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('18','AEROPUBLICA ','QUITO','MONTERREY','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('24','AMERICAN AIRLINES','QUITO','MIAMI','PANAMA','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('30','AEROMEXICO','QUITO','NEW YORK','MONTERREY','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('19','AEROPUBLICA ','GUAYAQUIL','MONTERREY','QUITO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('8','AMERICAN AIRLINES','GUAYAQUIL','LOS ANGELES','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('13','CONVIASA','QUITO','BOGOTA','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('25','AMERICAN AIRLINES','GUAYAQUIL','MIAMI','QUITO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('31','CONVIASA','GUAYAQUIL','NEW YORK','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('9','AIR EUROPA','QUITO','MADRID','MIAMI','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('14','CONVIASA','GUAYAQUIL','BOGOTA','QUITO','NO');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('17','AMERICAN AIRLINES','GUAYAQUIL','LONDRES','MIAMI','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('26','CONVIASA ','QUITO','MIAMI','NO','SI');
Insert into VUELO (IDVUELO,NOMBREAEROLINEA,ORIGEN,DESTINO,ESCALA,DISPONIBILIDAD) values ('32','CONVIASA','QUITO','NEW YORK','NO','SI');
--------------------------------------------------------
--  DDL for Index SYS_C008316
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008316" ON "VUELO" ("IDVUELO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Index SYS_C008331
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008331" ON "CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Index SYS_C008331
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008331" ON "CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Index SYS_C008316
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008316" ON "VUELO" ("IDVUELO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Trigger TRIGHOTEL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRIGHOTEL" 
BEFORE INSERT ON HOTEL
FOR EACH ROW 
BEGIN
SELECT HOTELUNO.NEXTVAL INTO :NEW.IDHOTEL FROM DUAL;
END;
/
ALTER TRIGGER "TRIGHOTEL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGUNO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRIGUNO" 
BEFORE INSERT ON cliente
FOR EACH ROW 
BEGIN 
SELECT uno.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRIGUNO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGUNO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRIGUNO" 
BEFORE INSERT ON cliente
FOR EACH ROW 
BEGIN 
SELECT uno.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRIGUNO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGHOTEL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRIGHOTEL" 
BEFORE INSERT ON HOTEL
FOR EACH ROW 
BEGIN
SELECT HOTELUNO.NEXTVAL INTO :NEW.IDHOTEL FROM DUAL;
END;
/
ALTER TRIGGER "TRIGHOTEL" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ACTUALIZAR_CLIENTE" (a IN CLIENTE.ID%TYPE,
                                    b IN CLIENTE.CEDULA%TYPE,
                                    c IN CLIENTE.NOMBRES%TYPE,
                                    d IN CLIENTE.APELLIDOS%TYPE,
                                    e IN CLIENTE.TELEFONO%TYPE,
                                    f IN CLIENTE.DIRECCION%TYPE,
                                    g IN CLIENTE.EMAIL%TYPE)
IS
BEGIN
    UPDATE CLIENTE SET CEDULA=b, NOMBRES=c,APELLIDOS=d,TELEFONO=e,DIRECCION=f,EMAIL=g WHERE ID=a;
END;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_HOTEL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ACTUALIZAR_HOTEL" (a IN HOTEL.IDHOTEL%TYPE,
                                    b IN HOTEL.NOMBRE%TYPE,
                                    c IN HOTEL.UBICACION%TYPE,
                                    d IN HOTEL.TELEFONO%TYPE,
                                    e IN HOTEL.DISPONIBILIDAD%TYPE,
                                    f IN HOTEL.SERVICIOS%TYPE)
IS
BEGIN
    UPDATE HOTEL SET NOMBRE=b, UBICACION=c,TELEFONO=d,DISPONIBILIDAD=e,SERVICIOS=f WHERE IDHOTEL=a;
END;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_VUELO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ACTUALIZAR_VUELO" (a IN VUELO.IDVUELO%TYPE,
                                    b IN VUELO.NOMBREAEROLINEA%TYPE,
                                    c IN VUELO.ORIGEN%TYPE,
                                    d IN VUELO.DESTINO%TYPE,
                                    e IN VUELO.ESCALA%TYPE,
                                    f IN VUELO.DISPONIBILIDAD%TYPE)
IS
BEGIN
    UPDATE VUELO SET NOMBREAEROLINEA=b, ORIGEN=c,DESTINO=d,ESCALA=e,DISPONIBILIDAD=f WHERE IDVUELO=a;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ELIMINAR_CLIENTE" (a IN CLIENTE.ID%TYPE)
IS 
BEGIN
    DELETE FROM CLIENTE WHERE ID=a;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_HOTEL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ELIMINAR_HOTEL" (a IN HOTEL.IDHOTEL%TYPE)
IS 
BEGIN
    DELETE FROM HOTEL WHERE IDHOTEL=a;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_VUELO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ELIMINAR_VUELO" (a IN VUELO.IDVUELO%TYPE)
IS 
BEGIN
    DELETE FROM VUELO WHERE IDVUELO=a;
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "REGISTRAR_CLIENTE" (a IN CLIENTE.ID%TYPE,
                                    b IN CLIENTE.CEDULA%TYPE,
                                    c IN CLIENTE.NOMBRES%TYPE,
                                    d IN CLIENTE.APELLIDOS%TYPE,
                                    e IN CLIENTE.TELEFONO%TYPE,
                                    f IN CLIENTE.DIRECCION%TYPE,
                                    g IN CLIENTE.EMAIL%TYPE)
IS
BEGIN
    INSERT INTO CLIENTE VALUES(a,b,c,d,e,f,g);
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRAR_HOTEL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "REGISTRAR_HOTEL" (a IN HOTEL.IDHOTEL%TYPE,
                                    b IN HOTEL.NOMBRE%TYPE,
                                    c IN HOTEL.UBICACION%TYPE,
                                    d IN HOTEL.TELEFONO%TYPE,
                                    e IN HOTEL.DISPONIBILIDAD%TYPE,
                                    f IN HOTEL.SERVICIOS%TYPE)
IS
BEGIN
    INSERT INTO HOTEL VALUES(a,b,c,d,e,f);
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRAR_VUELO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "REGISTRAR_VUELO" (a IN VUELO.IDVUELO%TYPE,
                                    b IN VUELO.NOMBREAEROLINEA%TYPE,
                                    c IN VUELO.ORIGEN%TYPE,
                                    d IN VUELO.DESTINO%TYPE,
                                    e IN VUELO.ESCALA%TYPE,
                                    f IN VUELO.DISPONIBILIDAD%TYPE)
IS
BEGIN
    INSERT INTO VUELO VALUES(a,b,c,d,e,f);
END;

/
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VUELO
--------------------------------------------------------

  ALTER TABLE "VUELO" ADD PRIMARY KEY ("IDVUELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT"  ENABLE;
