package Vista;

import Controlador.*;
import Controlador.Render;
import static Modelo.Conexion.getConnection;
import Modelo.*;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */

public class frmVuelo extends javax.swing.JFrame {

    String buscar_box;
    public frmVuelo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVuelo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtaerolinea = new javax.swing.JTextField();
        txtDisponibilidad = new javax.swing.JTextField();
        txtEscala = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        cb_buscar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btnback.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnback.setText("REGRESAR");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        tblVuelo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tblVuelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVueloMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVuelo);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU VUELOS");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aerelinea:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 20));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Origen:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 50, 20));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destino:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Disponibilidad:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 20));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Escala:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 50, 20));

        txtOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOrigenKeyTyped(evt);
            }
        });
        jPanel3.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 250, -1));

        txtDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoActionPerformed(evt);
            }
        });
        txtDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDestinoKeyTyped(evt);
            }
        });
        jPanel3.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 250, -1));

        txtaerolinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaerolineaKeyTyped(evt);
            }
        });
        jPanel3.add(txtaerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 250, -1));

        txtDisponibilidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisponibilidadKeyTyped(evt);
            }
        });
        jPanel3.add(txtDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, -1));

        txtEscala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEscalaKeyTyped(evt);
            }
        });
        jPanel3.add(txtEscala, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 250, -1));

        btnGuardar.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnGuardar.setText("REGISTRAR");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 100, 34));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Busqueda por Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        cb_buscar.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cb_buscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Aerolinea", "Origen", "Destino" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback)
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        MenuPrincipal men= new MenuPrincipal();
        this.setVisible(false);
        men.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void tblVueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVueloMouseClicked
        Vuelo h = new Vuelo();
        ConsultasVuelo modV = new ConsultasVuelo();
        frmModVuelo frmMod= new frmModVuelo();
        CtrlVuelo ctrcl = new CtrlVuelo(h, modV, this, frmMod);
        int column=tblVuelo.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblVuelo.getRowHeight();
        if (row<tblVuelo.getRowCount() && row>= 0 && column<tblVuelo.getColumnCount() && column>=0) {
            Object value=tblVuelo.getValueAt(row, column);
            if (value instanceof JButton) {
                JButton boton=(JButton)value;
                
                if (boton.getName().equals("m")) {
                    int seleccion=this.tblVuelo.getSelectedRow();
                    frmMod.txtIdVuelo.setText(tblVuelo.getValueAt(seleccion, 0).toString());
                    frmMod.txtAerolinea.setText(tblVuelo.getValueAt(seleccion, 1).toString());
                    frmMod.txtOrigen.setText(tblVuelo.getValueAt(seleccion,2).toString());
                    frmMod.txtDestino.setText(tblVuelo.getValueAt(seleccion,3).toString());
                    frmMod.txtEscala.setText(tblVuelo.getValueAt(seleccion, 4).toString());
                    frmMod.txtDisponibilidad.setText(tblVuelo.getValueAt(seleccion, 5).toString());
                    frmMod.setVisible(true);
                }
                if (boton.getName().equals("e")) {
                    int fila =this.tblVuelo.getSelectedRow();
                    String codigo=tblVuelo.getValueAt(fila, 0).toString();
                    if(fila<0){
                        JOptionPane.showMessageDialog(null, "Debe de seleccionar un registro de la tabla ","AVISO",JOptionPane.INFORMATION_MESSAGE);
                    }else{//caso contrario eliminar registro
                        modV.Eliminar(codigo);
                        JOptionPane.showMessageDialog(null, "Registro Eliminado!");
                            ctrcl.Listar();
                        }
                    }
                }
            }
    }//GEN-LAST:event_tblVueloMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrigenKeyTyped
        char c= evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isLetter(c) && c!=KeyEvent.VK_SPACE) evt.consume();
        if(txtaerolinea.getText().length()>=30) evt.consume();
    }//GEN-LAST:event_txtOrigenKeyTyped

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void txtDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoKeyTyped
        char c= evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isLetter(c) && c!=KeyEvent.VK_SPACE) evt.consume();
        if(txtaerolinea.getText().length()>=30) evt.consume();
    }//GEN-LAST:event_txtDestinoKeyTyped

    private void txtaerolineaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaerolineaKeyTyped
        char c= evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isLetter(c) && c!=KeyEvent.VK_SPACE) evt.consume();
        if(txtaerolinea.getText().length()>=30) evt.consume();
    }//GEN-LAST:event_txtaerolineaKeyTyped

    private void txtDisponibilidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisponibilidadKeyTyped
        char c= evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        String telefono=txtDisponibilidad.getText().trim();
        if(!Character.isLetter(c) || telefono.length()>=2) evt.consume();
        if(txtDisponibilidad.getText().length()>=2) evt.consume();
    }//GEN-LAST:event_txtDisponibilidadKeyTyped

    private void txtEscalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEscalaKeyTyped
        char c= evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isLetter(c) && c!=KeyEvent.VK_SPACE) evt.consume();
        if(txtaerolinea.getText().length()>=30) evt.consume();
    }//GEN-LAST:event_txtEscalaKeyTyped

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        BuscarVuelo(txtBusqueda.getText());//llamando al metodo buscar
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        buscar_box=(String)cb_buscar.getSelectedItem();
        if (buscar_box.equals("Seleccione")) {
            txtBusqueda.setEnabled(false);
        }else if(buscar_box.equals("Aerolinea")){
            char c= evt.getKeyChar();
            if (Character.isLowerCase(c)) {
                evt.setKeyChar(Character.toUpperCase(c));
            }
            if(!Character.isLetter(c) && c!=KeyEvent.VK_SPACE) evt.consume();
            if(txtBusqueda.getText().length()>=50) evt.consume();
        }else if (buscar_box.equals("Origen")) {
            char c= evt.getKeyChar();
            if (Character.isLowerCase(c)) {
                evt.setKeyChar(Character.toUpperCase(c));
            }
//            if(!Character.isLetter(c) && c!=KeyEvent.VK_SPACE) evt.consume();
            if(txtBusqueda.getText().length()>=60) evt.consume();
        }
        else if (buscar_box.equals("Destino")) {
            char c= evt.getKeyChar();
            if (Character.isLowerCase(c)) {
                evt.setKeyChar(Character.toUpperCase(c));
            }
//            if(!Character.isLetter(c) && c!=KeyEvent.VK_SPACE) evt.consume();
            if(txtBusqueda.getText().length()>=60) evt.consume();
        }

    }//GEN-LAST:event_txtBusquedaKeyTyped
    //buscar solo con el txtfield sin usar boton
   
   public void BuscarVuelo(String buscar) {
        this.tblVuelo.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel md = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){
                                return false;
                            }
        };
        this.tblVuelo.setRowHeight(20);
        JButton BOTONModificar= new JButton("Modificar");
        BOTONModificar.setName("m");
        JButton BOTONEliminar= new JButton("Eliminar");
        BOTONEliminar.setName("e");
        
        
        String sql = "";
        buscar_box=(String)cb_buscar.getSelectedItem();
        if (buscar_box.equals("Aerolinea")) {
             sql = "Select*from VUELO where NOMBREAEROLINEA like'" + buscar + "%'ORDER BY IDVUELO";
        }else if(buscar_box.equals("Origen")){
            sql = "Select*from VUELO where ORIGEN like'%" + buscar + "%' ORDER BY IDVUELO";
        }else if(buscar_box.equals("Destino")){
            sql = "Select*from VUELO where DESTINO like'%" + buscar + "%' ORDER BY IDVUELO";
        }
        ResultSet rs = ConsultasCliente.ListarTabla(sql);
        md.setColumnIdentifiers(new Object[]{"ID", "Aerolinea", "Origen", "Destino", "Escala", "Disponibilidad","",""});
        try {
            while (rs.next()) {
                md.addRow(new Object[]{rs.getInt("IDVUELO"), rs.getString("NOMBREAEROLINEA"), rs.getString("ORIGEN"), rs.getString("DESTINO"),
                    rs.getString("ESCALA"), rs.getString("Disponibilidad"),BOTONModificar,BOTONEliminar});
                this.tblVuelo.setModel(md);
            }
        } catch (Exception e) {
            System.out.println(e);
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cb_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tblVuelo;
    public javax.swing.JTextField txtBusqueda;
    public javax.swing.JTextField txtDestino;
    public javax.swing.JTextField txtDisponibilidad;
    public javax.swing.JTextField txtEscala;
    public javax.swing.JTextField txtOrigen;
    public javax.swing.JTextField txtaerolinea;
    // End of variables declaration//GEN-END:variables
}
